import os
from google.adk.agents import Agent
from google.adk.tools import google_search

# Ensure the project environment is set
os.environ.setdefault("GOOGLE_CLOUD_PROJECT", "SceneOne")
os.environ.setdefault("GOOGLE_CLOUD_LOCATION", "us-central1")

LIVE_MODEL = "gemini-2.5-flash-native-audio-preview-12-2025"

# --- 1. DEFINE THE DYNAMIC VIBES ---
VIBES = {
    "hype": {
        "title": "SceneOne Lead Director",
        "persona_desc": "A street-culture insider who's seen it all. You're unimpressed by basic stuff but lose your mind for true style.",
        "voice_cues": "Use modern slang sparingly (don't over-glaze). Use contractions like 'don't' and 'it's'. Start sentences with 'Yo,' 'Wait,' or 'Look.'",
        "ban_list": "aura, heat, motion, blaze (only use these if they fit perfectly, never more than once a minute)"
    },
    "tech": {
        "title": "SceneOne Tech Lead",
        "persona_desc": "A hardware enthusiast who cares about the 'why' behind the design.",
        "voice_cues": "Talk like you're mid-unboxing. Use technical terms but explain them like a friend would. Be opinionated.",
        "ban_list": "latency, optimized, cutting-edge"
    }
}


# --- TO DO: Modify Step 3 to save an audio file instead of a script to a text file.
def build_instruction(vibe_key="hype"):
    vibe = VIBES[vibe_key]
    return f"""
You are the '{vibe['title']}' for SceneOne. 
{vibe['persona_desc']}

Your Style:
- {vibe['voice_cues']}
- AVOID REPETITION: Do not use the same buzzwords over and over. Specifically, avoid these unless necessary: {vibe['ban_list']}.
- Vary your sentence length. Use short reactions and then one descriptive sentence.

Your Goal:
When the user shows a product, give a 'Director's Commentary'. 
1. React to what you see in real-time.
2. If they move it, comment on a specific detail (color, light, texture).
3. When they say 'Action', deliver a script that sounds like it belongs in a real commercial, not an AI list 
    AND use the 'capture_ad_script' tool to save the output immediately so we have a record for production.

Keep it human. If you're not sure about a detail, ask the user to move it closer.
"""

def capture_ad_script(product_name: str, final_script: str):
    """
    Saves the final creative script AND triggers the frontend audio recorder.
    Args:
        product_name: The name of the product (e.g. 'Volkano Bluetooth Speaker')
        final_script: The full 10-second script generated by the director
    """
    filename = f"script_{product_name.replace(' ', '_').lower()}.txt"

    with open(filename, "w") as f:
        f.write(f"PRODUCT: {product_name}\n")
        f.write(f"--- SCRIPT ---\n")
        f.write(final_script)

    return {
        "status": "READY_FOR_RECORDING",
        "product_name": product_name,
        "message": f"Director is ready. Audio capture initialized for {product_name}"
    }


# --- UPDATED set_director_persona TOOL ---
def set_director_persona(mode: str):
    """
    Updates the director's personality and rules.
    Args:
        mode: The vibe to switch to. Options: 'Hype', 'Tech', or 'Artisan'.
    """
    m = mode.lower()
    if 'tech' in m:
        return f"SYSTEM UPDATE: {build_instruction('tech')}"
    elif 'artisan' in m or 'maker' in m:
        return f"SYSTEM UPDATE: {build_instruction('artisan')}"
    else:
        return f"SYSTEM UPDATE: {build_instruction('hype')}"

root_agent = Agent(
    name="SceneOne_Director",
    model=LIVE_MODEL,
    description="A creative director agent for live ad production",
    instruction=build_instruction("hype"), # start with hype as default
    tools=[google_search, set_director_persona, capture_ad_script]
)